#%YAML 1.2
#
# @file .coveralls.yml
#

# The name of the service uploading the data
service_name: travis-ci

# Where to find the code coverage report
coverage_clover: ${TRAVIS_BUILD_DIR}/logs/coverage/clover.xml

# Unsure what this does
json_path: ${TRAVIS_BUILD_DIR}/logs/coverage/coveralls-upload.json
